# 基站
eNodeB:
  host.port: 10000
# 基站广播网段
  broadcast.port: 65533
# 广播扫描参数
  scan.time: 10

# eps 网络功能实体
EPS: 
  mme.host: 127.0.0.1:12346
  pgw.host: 127.0.0.1:12347
  hss.host: 127.0.0.1:12348

# ims 网络功能实体
# P-CSCF和I-CSCF对于SIP消息主要进行转发，功能很少
# S-CSCF为最上行的节点，功能较多，把IMS域的所有功能实体坐在一起叫CSCF
IMS: 
  x-cscf.host: 127.0.0.1:54321
  pcrf.host: 127.0.0.1:54324

# 数据库配置信息
mysql: 
  host: "root:@tcp(127.0.0.1:3306)/volte?charset=utf8&parseTime=True&loc=Local"

