# 基站
eNodeB:
  host.port: 10000
# 基站广播网段
  broadcast.port: 65533
# 广播扫描参数
  scan.time: 10

# eps 网络功能实体
EPS: 
  mme.host: 127.0.0.1:12346
  pgw.host: 127.0.0.1:12347
  hss.host: 127.0.0.1:12348

# ims 网络功能实体
IMS: 
  p-cscf: 127.0.0.1:54321
  i-cscf: 127.0.0.1:54322
  s-cscf: 127.0.0.1:54323
  pcrf: 127.0.0.1:54324

# 数据库配置信息
mysql: 
  host: "root:@tcp(127.0.0.1:3306)/volte?charset=utf8&parseTime=True&loc=Local"

