# 基站
eNodeB:
  server.port: 10000
# 基站广播端口
  broadcast.port: 65532
# 广播扫描参数
  scan.time: 3
# 修改TAI值模拟不同的基站
# 统一局域网内的不同设备上部署不同基站
  beatheart.time: 10

hebeiyidong:
  # epc 网络功能实体
  enb.id: "100231511300031"
  pgw.host: 114.115.174.184:12348
  pgw.dhcp : 10.0.1.0/24
  # ims 网络功能实体
  p-cscf.host: 127.0.0.1:54321
  i-cscf.host: 127.0.0.1:54322
  s-cscf.host: 127.0.0.1:54323
  domain: hebeiyidong.3gpp.net
chongqingdianxin:
  # epc 网络功能实体
  enb.id: "100231511300032"
  pgw.host: 114.115.174.184:12347
  pgw.dhcp : 10.0.1.0/24
  # ims 网络功能实体
  p-cscf.host: 127.0.0.1:44321
  i-cscf.host: 127.0.0.1:44322
  s-cscf.host: 127.0.0.1:44323
  domain: chongqingdianxin.3gpp.net

hss:
  host: 127.0.0.1:7777

